### ISSUE TITLE
Samples Not Working - Python 2.7.11 Windows With py documentdb V2.0

### ISSUE THREAD

**Issue by kradNZ** [Azure/azure-cosmos-python#70]
Samples Not Working - Python 2.7.11 Windows With py documentdb V2.0

Actually not sure if I've ever got the samples working.

In addition to that I have a project that was working with pydocumentdb V1.9 but it no longer works with V2.0.

It seems like many methods no longer return what they used to?  Eg: client.QueryDatabases()

Error messages all point to an issue with iterators?  Not sure how to progress from here.

**Comment by moderakh** [comment]
@kradNZ
Could you please provide more information on what the error message is? possibly the stacktrace?

**Comment by rnagpal** [comment]
@kradNZ Could you send us the sample code with the expected and actual results?

**Comment by ilyauts** [comment]
>> python Program.py
Traceback (most recent call last):
  File "Program.py", line 29, in <module>
    HOST = cfg.settings['host']
AttributeError: 'module' object has no attribute 'settings'

Is the response out of the box for the samples.

**Comment by HussainMir** [comment]
These are defined in the [config.py](https://github.com/Azure/azure-documentdb-python/blob/master/samples/Shared/config.py) file. This is a shared file across projects in the solution. And this works when we run any project as a whole not the individual file program.py.

**Comment by HussainMir** [comment]
@rnagpal Looks like this is a duplicate of https://github.com/Azure/azure-documentdb-python/issues/94

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
